const NODES = {
    productsList: document.querySelector('#goods-list'),
    absentProductsList: document.querySelector('#out-of-stuff-list'),
    checkbox_wrapper: document.querySelector('.checkbox-wrapper'),
    checkboxes: document.querySelectorAll('.checkbox-input'),
    quantity_info: document.querySelector('.cart__quantity-info'),
    navigation_carts: document.querySelectorAll('.navigation__cart'),
    navigation_items: document.querySelectorAll('.navigation__item'),
    cartQuantity: document.querySelector('.cart__quantity-badge'),
    outOfStuff: document.querySelector('.out-of-stuff-list'),
    delivery: document.querySelector('.delivery'),
    delivery_chosenItems: document.querySelectorAll('.delivery__chosen-item'),
    deliveringItems: document.querySelector('.delivery__items'),
    paymentMethod: document.querySelector('.payment-method'),
    totalInfo_block: document.querySelector('.total-info'),
    totalInfo_title: document.querySelector('.total-info__title'),
    totalInfo_no_discount: document.querySelector('.total-info__no-discount'),
    totalInfo_discount: document.querySelector('.total-info__discount'),
    totalInfo_delivery: document.querySelector('.total-info__delivery'),
    totalInfo_address: document.querySelector('.total-info__address'),
    totalInfo_payment: document.querySelector('.total-info__payment'),
    input_debitConfirm: document.getElementById('checkbox_direct-debit-confirm'),
    recipientForm: document.querySelector('.recipient'),
    recipient_form: document.getElementById('recipient-form'),
    form_inputs: document.querySelectorAll('.form__input'),
    input_firstName: document.getElementById('firstname'),
    input_lastName: document.getElementById('lastname'),
    input_email: document.getElementById('email'),
    input_phone: document.getElementById('phone'),
    input_inn: document.getElementById('inn'),
    modal: document.querySelector('.cart__modal-wrapper'),
    modal_payment: document.querySelector('.modal__payment'),
    modal_delivery: document.querySelector('.modal__delivery'),
    modal_content: document.querySelector('.modal__content'),
    delivery_addresses: document.querySelector('.delivery-addresses'),
    modal_deliveryMethod: document.querySelectorAll('.delivery-method'),
    modal_confirmBtn: document.querySelectorAll('.modal__btn'),
    modal_closeBtn: document.querySelectorAll('.modal__close'),
    radioItems_form: document.getElementById('form_radio-items'),
    btns_delete: document.querySelectorAll('.actions__delete'),
    btns_favorite: document.querySelectorAll('.actions__isFavorite'),
    btn_order: document.querySelector('.total-info__order-btn'),
}

export default NODES;